version: "3"

services:
  chat-server:
    build:
      context: ./server
    ports:
      - 6969:6969
    depends_on:
      - mongo-database

  mongo-database:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - mongod:/data/db

volumes:
  mongod: